### ISSUE TITLE
Clear tag input field after selecting new tag

### ISSUE THREAD

**Issue by jburell** [johangus/rubber-ducker#1]

**Comment by JGUSTA75** [comment]
Fixed

**Comment by JGUSTA75** [comment]
@jburell  Hur stänger man den här 😅

**Comment by jburell** [comment]
Fixed with 6275bfb

**Comment by jburell** [comment]
> @jburell Hur stänger man den här sweat_smile

Fixade! :) Verkar som att kanske bara ägaren av issuen kan? Borde vi kanske ändra på.
